version: 2 # use CircleCI 2.0

jobs:
  build:

    working_directory: ~/hqtrivia-bot

    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout # check out source code to the working directory

      - restore_cache: # restore cache if dependencies have not changed since last run in this branch
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run: # install and activate virtual environment with pip
          name: Install Pipenv
          command: |
            sudo pip install pipenv
            pipenv install

      - save_cache: # save dependency cache
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"

      - run: # run tests
          name: Run Tests
          command: |
            mkdir test-reports
            pipenv run "pytest --junitxml=test-reports/junit.xml"

      - store_test_results: # store test reports
          path: test-reports

      - store_artifacts: # store artifacts
          path: test-reports
