version: 2 # use CircleCI 2.0

jobs:
  build:

    working_directory: ~/hqtrivia-bot

    docker:
      - image: circleci/python:3.6-stretch

    steps:
      - checkout # check out source code to the working directory

      - restore_cache: # restore cache if dependencies have not changed since last run in this branch
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run: # install and activate virtual environment with pip
          name: Install Pipenv
          command: |
            sudo pip install pipenv --upgrade
            pipenv install --dev
            pipenv python -m nltk.downloader stopwords

      - save_cache: # save dependency cache
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"

      - run: # run tests
          name: Run Tests
          command: |
            mkdir test-reports
            pipenv run cache import
            pipenv run test -s --junitxml=test-reports/junit.xml

      - run: # run lint
          name: Run Lint
          command: |
            pipenv run lint

      - store_test_results: # store test reports
          path: test-reports

      - store_artifacts: # store artifacts
          path: test-reports
